version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - back-tier
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
  #elasticsearch for applications
  elasticsearch:
    build: elasticsearch/
    ports:
        - "9200"
        - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      discovery.zen.ping.unicast.hosts: elasticsearch
      cluster.name: dockerCluster #elasticsearch dashboards has issues with cluster names with "-"
    networks:
    - back-tier
    - front-tier

  #elasticsearch container with index containing metrics for Grafana Dashboards
  elasticsearch-monitoring:
    build: elasticsearch-monitoring/
    ports:
        - "9200"
        - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      discovery.zen.ping.unicast.hosts: elasticsearch-monitoring
      cluster.name: dockerClusterMonitoring #elasticsearch grafana dashboard has issues with cluster names with "-"
    networks:
    - back-tier
    - front-tier

  logstash:
    build: logstash/
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - back-tier
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - back-tier
    depends_on:
      - elasticsearch

  #will send metrics to elasticsearch monitoring
  #this container will fail until both elasticsearch containers are up and running
  #wait until both containers are working and run this container again
  #executing again docker-composer up -d
  es-monitor:
    build: es-monitor/
    container_name: es-monitor
    environment:
      ES_METRICS_CLUSTER_URL: "http://elasticsearch:9200"
      ES_METRICS_INDEX_NAME: "elasticsearch_metrics"
      ES_METRICS_MONITORING_CLUSTER_URL: "http://elasticsearch-monitoring:9200"
    networks:
      - back-tier
    depends_on:
      - elasticsearch
      - elasticsearch-monitoring
